// This file is auto-generated by @hey-api/openapi-ts

export const $AuthOptions = {
    type: 'object',
    properties: {
        basic: {
            type: 'string',
            description: 'Basic auth in user:pass form'
        },
        headers: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            }
        },
        cookies: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'Cookie strings like "name=value"'
        },
        loginUrl: {
            type: 'string'
        },
        loginUserSelector: {
            type: 'string'
        },
        loginPassSelector: {
            type: 'string'
        },
        loginSubmitSelector: {
            type: 'string'
        },
        loginUser: {
            type: 'string'
        },
        loginPass: {
            type: 'string'
        }
    }
} as const;

export const $ScrapeRequest = {
    type: 'object',
    required: ['url'],
    properties: {
        url: {
            type: 'string'
        },
        headless: {
            type: 'boolean',
            default: false
        },
        auth: {
            '$ref': '#/components/schemas/AuthOptions'
        },
        timeoutSeconds: {
            type: 'integer',
            default: 30
        }
    }
} as const;

export const $CrawlRequest = {
    type: 'object',
    required: ['url'],
    properties: {
        url: {
            type: 'string'
        },
        maxDepth: {
            type: 'integer',
            default: 2
        },
        maxPages: {
            type: 'integer',
            default: 200
        },
        headless: {
            type: 'boolean',
            default: false
        },
        auth: {
            '$ref': '#/components/schemas/AuthOptions'
        },
        timeoutSeconds: {
            type: 'integer',
            default: 30
        }
    }
} as const;

export const $Job = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        kind: {
            type: 'string',
            enum: ['scrape', 'crawl']
        },
        status: {
            type: 'string',
            enum: ['queued', 'running', 'succeeded', 'failed']
        },
        createdAt: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        params: {
            type: 'object'
        },
        resultPath: {
            type: 'string'
        },
        error: {
            type: 'string'
        }
    }
} as const;

export const $JobList = {
    type: 'object',
    properties: {
        jobs: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Job'
            }
        }
    }
} as const;