// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthzData, GetHealthzResponses, GetV1JobsByIdData, GetV1JobsByIdResponses, GetV1JobsByIdResultsData, GetV1JobsByIdResultsResponses, GetV1JobsData, GetV1JobsResponses, PostV1CrawlData, PostV1CrawlResponses, PostV1ResearchData, PostV1ResearchResponses, PostV1ScrapeData, PostV1ScrapeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const getHealthz = <ThrowOnError extends boolean = false>(options?: Options<GetHealthzData, ThrowOnError>) => (options?.client ?? client).get<GetHealthzResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Scrape a single page
 */
export const postV1Scrape = <ThrowOnError extends boolean = false>(options: Options<PostV1ScrapeData, ThrowOnError>) => (options.client ?? client).post<PostV1ScrapeResponses, unknown, ThrowOnError>({
    url: '/v1/scrape',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Crawl a site
 */
export const postV1Crawl = <ThrowOnError extends boolean = false>(options: Options<PostV1CrawlData, ThrowOnError>) => (options.client ?? client).post<PostV1CrawlResponses, unknown, ThrowOnError>({
    url: '/v1/crawl',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deep research across multiple sources
 */
export const postV1Research = <ThrowOnError extends boolean = false>(options: Options<PostV1ResearchData, ThrowOnError>) => (options.client ?? client).post<PostV1ResearchResponses, unknown, ThrowOnError>({
    url: '/v1/research',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List jobs
 */
export const getV1Jobs = <ThrowOnError extends boolean = false>(options?: Options<GetV1JobsData, ThrowOnError>) => (options?.client ?? client).get<GetV1JobsResponses, unknown, ThrowOnError>({ url: '/v1/jobs', ...options });

/**
 * Get a job
 */
export const getV1JobsById = <ThrowOnError extends boolean = false>(options: Options<GetV1JobsByIdData, ThrowOnError>) => (options.client ?? client).get<GetV1JobsByIdResponses, unknown, ThrowOnError>({ url: '/v1/jobs/{id}', ...options });

/**
 * Get job results
 */
export const getV1JobsByIdResults = <ThrowOnError extends boolean = false>(options: Options<GetV1JobsByIdResultsData, ThrowOnError>) => (options.client ?? client).get<GetV1JobsByIdResultsResponses, unknown, ThrowOnError>({ url: '/v1/jobs/{id}/results', ...options });
