// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteV1AuthProfilesByNameData, DeleteV1AuthProfilesByNameResponses, DeleteV1JobsByIdData, DeleteV1JobsByIdResponses, GetHealthzData, GetHealthzErrors, GetHealthzResponses, GetV1AuthProfilesData, GetV1AuthProfilesResponses, GetV1JobsByIdData, GetV1JobsByIdResponses, GetV1JobsByIdResultsData, GetV1JobsByIdResultsResponses, GetV1JobsData, GetV1JobsResponses, PostV1AuthExportData, PostV1AuthExportResponses, PostV1AuthImportData, PostV1AuthImportResponses, PostV1CrawlData, PostV1CrawlResponses, PostV1ResearchData, PostV1ResearchResponses, PostV1ScrapeData, PostV1ScrapeResponses, PutV1AuthProfilesByNameData, PutV1AuthProfilesByNameResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const getHealthz = <ThrowOnError extends boolean = false>(options?: Options<GetHealthzData, ThrowOnError>) => (options?.client ?? client).get<GetHealthzResponses, GetHealthzErrors, ThrowOnError>({ url: '/healthz', ...options });

/**
 * List auth profiles
 */
export const getV1AuthProfiles = <ThrowOnError extends boolean = false>(options?: Options<GetV1AuthProfilesData, ThrowOnError>) => (options?.client ?? client).get<GetV1AuthProfilesResponses, unknown, ThrowOnError>({ url: '/v1/auth/profiles', ...options });

/**
 * Delete auth profile
 */
export const deleteV1AuthProfilesByName = <ThrowOnError extends boolean = false>(options: Options<DeleteV1AuthProfilesByNameData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1AuthProfilesByNameResponses, unknown, ThrowOnError>({ url: '/v1/auth/profiles/{name}', ...options });

/**
 * Upsert auth profile
 */
export const putV1AuthProfilesByName = <ThrowOnError extends boolean = false>(options: Options<PutV1AuthProfilesByNameData, ThrowOnError>) => (options.client ?? client).put<PutV1AuthProfilesByNameResponses, unknown, ThrowOnError>({
    url: '/v1/auth/profiles/{name}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Import auth vault
 *
 * Import auth vault from a file in the data directory.
 * The path must be a simple filename (no directory separators or path traversal).
 * The file is resolved relative to the configured DATA_DIR.
 *
 */
export const postV1AuthImport = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthImportData, ThrowOnError>) => (options.client ?? client).post<PostV1AuthImportResponses, unknown, ThrowOnError>({
    url: '/v1/auth/import',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Export auth vault
 *
 * Export auth vault to a file in the data directory.
 * The path must be a simple filename (no directory separators or path traversal).
 * The file is resolved relative to the configured DATA_DIR.
 *
 */
export const postV1AuthExport = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthExportData, ThrowOnError>) => (options.client ?? client).post<PostV1AuthExportResponses, unknown, ThrowOnError>({
    url: '/v1/auth/export',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Scrape a single page
 */
export const postV1Scrape = <ThrowOnError extends boolean = false>(options: Options<PostV1ScrapeData, ThrowOnError>) => (options.client ?? client).post<PostV1ScrapeResponses, unknown, ThrowOnError>({
    url: '/v1/scrape',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Crawl a site
 */
export const postV1Crawl = <ThrowOnError extends boolean = false>(options: Options<PostV1CrawlData, ThrowOnError>) => (options.client ?? client).post<PostV1CrawlResponses, unknown, ThrowOnError>({
    url: '/v1/crawl',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deep research across multiple sources
 */
export const postV1Research = <ThrowOnError extends boolean = false>(options: Options<PostV1ResearchData, ThrowOnError>) => (options.client ?? client).post<PostV1ResearchResponses, unknown, ThrowOnError>({
    url: '/v1/research',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List jobs
 */
export const getV1Jobs = <ThrowOnError extends boolean = false>(options?: Options<GetV1JobsData, ThrowOnError>) => (options?.client ?? client).get<GetV1JobsResponses, unknown, ThrowOnError>({ url: '/v1/jobs', ...options });

/**
 * Cancel a job
 */
export const deleteV1JobsById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1JobsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteV1JobsByIdResponses, unknown, ThrowOnError>({ url: '/v1/jobs/{id}', ...options });

/**
 * Get a job
 */
export const getV1JobsById = <ThrowOnError extends boolean = false>(options: Options<GetV1JobsByIdData, ThrowOnError>) => (options.client ?? client).get<GetV1JobsByIdResponses, unknown, ThrowOnError>({ url: '/v1/jobs/{id}', ...options });

/**
 * Get job results
 */
export const getV1JobsByIdResults = <ThrowOnError extends boolean = false>(options: Options<GetV1JobsByIdResultsData, ThrowOnError>) => (options.client ?? client).get<GetV1JobsByIdResultsResponses, unknown, ThrowOnError>({ url: '/v1/jobs/{id}/results', ...options });
