// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetHealthzResponse, PostV1ScrapeData, PostV1ScrapeResponse, PostV1CrawlData, PostV1CrawlResponse, PostV1ResearchData, PostV1ResearchResponse, GetV1JobsResponse, GetV1JobsByIdData, GetV1JobsByIdResponse, GetV1JobsByIdResultsData, GetV1JobsByIdResultsResponse } from './types.gen';

/**
 * Health check
 * @returns unknown OK
 * @throws ApiError
 */
export const getHealthz = (): CancelablePromise<GetHealthzResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/healthz'
}); };

/**
 * Scrape a single page
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Job Job created
 * @throws ApiError
 */
export const postV1Scrape = (data: PostV1ScrapeData): CancelablePromise<PostV1ScrapeResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/scrape',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * Crawl a site
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Job Job created
 * @throws ApiError
 */
export const postV1Crawl = (data: PostV1CrawlData): CancelablePromise<PostV1CrawlResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/crawl',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * Deep research across multiple sources
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Job Job created
 * @throws ApiError
 */
export const postV1Research = (data: PostV1ResearchData): CancelablePromise<PostV1ResearchResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/v1/research',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * List jobs
 * @returns JobList Job list
 * @throws ApiError
 */
export const getV1Jobs = (): CancelablePromise<GetV1JobsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/v1/jobs'
}); };

/**
 * Get a job
 * @param data The data for the request.
 * @param data.id
 * @returns Job Job
 * @throws ApiError
 */
export const getV1JobsById = (data: GetV1JobsByIdData): CancelablePromise<GetV1JobsByIdResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/v1/jobs/{id}',
    path: {
        id: data.id
    }
}); };

/**
 * Get job results
 * @param data The data for the request.
 * @param data.id
 * @returns string Results (JSONL)
 * @throws ApiError
 */
export const getV1JobsByIdResults = (data: GetV1JobsByIdResultsData): CancelablePromise<GetV1JobsByIdResultsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/v1/jobs/{id}/results',
    path: {
        id: data.id
    }
}); };