// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8741' | (string & {});
};

export type ExtractOptions = {
    /**
     * Template name (e.g. "article", "product")
     */
    template?: string;
    /**
     * Validate extraction against schema if present
     */
    validate?: boolean;
};

export type PipelineOptions = {
    preProcessors?: Array<string>;
    postProcessors?: Array<string>;
    transformers?: Array<string>;
};

export type ResearchEvidence = {
    url?: string;
    title?: string;
    snippet?: string;
    score?: number;
    simhash?: number;
    clusterId?: string;
    confidence?: number;
    citationUrl?: string;
};

export type ResearchEvidenceCluster = {
    id?: string;
    label?: string;
    confidence?: number;
    evidence?: Array<ResearchEvidence>;
};

export type ResearchCitation = {
    url?: string;
    anchor?: string;
    canonical?: string;
};

export type ResearchResult = {
    query?: string;
    summary?: string;
    confidence?: number;
    evidence?: Array<ResearchEvidence>;
    clusters?: Array<ResearchEvidenceCluster>;
    citations?: Array<ResearchCitation>;
};

export type HeaderKv = {
    key?: string;
    value?: string;
};

export type Cookie = {
    name?: string;
    value?: string;
    domain?: string;
    path?: string;
};

export type Token = {
    kind?: 'bearer' | 'basic' | 'api_key';
    value?: string;
    header?: string;
    query?: string;
    cookie?: string;
};

export type LoginFlow = {
    url?: string;
    userSelector?: string;
    passSelector?: string;
    submitSelector?: string;
    username?: string;
    password?: string;
};

export type TargetPreset = {
    name?: string;
    hostPatterns?: Array<string>;
    profile?: string;
    headers?: Array<HeaderKv>;
    cookies?: Array<Cookie>;
    tokens?: Array<Token>;
};

export type AuthProfile = {
    name?: string;
    parents?: Array<string>;
    headers?: Array<HeaderKv>;
    cookies?: Array<Cookie>;
    tokens?: Array<Token>;
    login?: LoginFlow;
    presets?: Array<TargetPreset>;
};

export type AuthVault = {
    version?: string;
    profiles?: Array<AuthProfile>;
    presets?: Array<TargetPreset>;
};

export type AuthProfilesResponse = {
    profiles?: Array<AuthProfile>;
};

export type AuthVaultImport = {
    path: string;
};

export type AuthVaultExport = {
    path: string;
};

export type StatusResponse = {
    status?: string;
};

export type AuthOptions = {
    /**
     * Basic auth in user:pass form
     */
    basic?: string;
    headers?: {
        [key: string]: string;
    };
    /**
     * Cookie strings like "name=value"
     */
    cookies?: Array<string>;
    /**
     * Query params applied to the request URL
     */
    query?: {
        [key: string]: string;
    };
    loginUrl?: string;
    loginUserSelector?: string;
    loginPassSelector?: string;
    loginSubmitSelector?: string;
    loginUser?: string;
    loginPass?: string;
};

export type ScrapeRequest = {
    url: string;
    headless?: boolean;
    playwright?: boolean;
    authProfile?: string;
    auth?: AuthOptions;
    extract?: ExtractOptions;
    pipeline?: PipelineOptions;
    timeoutSeconds?: number;
    incremental?: boolean;
};

export type CrawlRequest = {
    url: string;
    maxDepth?: number;
    maxPages?: number;
    headless?: boolean;
    playwright?: boolean;
    authProfile?: string;
    auth?: AuthOptions;
    extract?: ExtractOptions;
    pipeline?: PipelineOptions;
    timeoutSeconds?: number;
    incremental?: boolean;
};

export type ResearchRequest = {
    query: string;
    urls: Array<string>;
    maxDepth?: number;
    maxPages?: number;
    headless?: boolean;
    playwright?: boolean;
    authProfile?: string;
    auth?: AuthOptions;
    extract?: ExtractOptions;
    pipeline?: PipelineOptions;
    timeoutSeconds?: number;
    incremental?: boolean;
};

export type Job = {
    id?: string;
    kind?: 'scrape' | 'crawl' | 'research';
    status?: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
    createdAt?: string;
    updatedAt?: string;
    params?: {
        [key: string]: unknown;
    };
    resultPath?: string;
    error?: string;
};

export type JobList = {
    jobs?: Array<Job>;
};

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetV1AuthProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/profiles';
};

export type GetV1AuthProfilesResponses = {
    /**
     * Auth profiles
     */
    200: AuthProfilesResponse;
};

export type GetV1AuthProfilesResponse = GetV1AuthProfilesResponses[keyof GetV1AuthProfilesResponses];

export type DeleteV1AuthProfilesByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/v1/auth/profiles/{name}';
};

export type DeleteV1AuthProfilesByNameResponses = {
    /**
     * Deleted
     */
    200: StatusResponse;
};

export type DeleteV1AuthProfilesByNameResponse = DeleteV1AuthProfilesByNameResponses[keyof DeleteV1AuthProfilesByNameResponses];

export type PutV1AuthProfilesByNameData = {
    body: AuthProfile;
    path: {
        name: string;
    };
    query?: never;
    url: '/v1/auth/profiles/{name}';
};

export type PutV1AuthProfilesByNameResponses = {
    /**
     * Auth profile saved
     */
    200: AuthProfile;
};

export type PutV1AuthProfilesByNameResponse = PutV1AuthProfilesByNameResponses[keyof PutV1AuthProfilesByNameResponses];

export type PostV1AuthImportData = {
    body: AuthVaultImport;
    path?: never;
    query?: never;
    url: '/v1/auth/import';
};

export type PostV1AuthImportResponses = {
    /**
     * Imported
     */
    200: StatusResponse;
};

export type PostV1AuthImportResponse = PostV1AuthImportResponses[keyof PostV1AuthImportResponses];

export type PostV1AuthExportData = {
    body: AuthVaultExport;
    path?: never;
    query?: never;
    url: '/v1/auth/export';
};

export type PostV1AuthExportResponses = {
    /**
     * Exported
     */
    200: StatusResponse;
};

export type PostV1AuthExportResponse = PostV1AuthExportResponses[keyof PostV1AuthExportResponses];

export type PostV1ScrapeData = {
    body: ScrapeRequest;
    path?: never;
    query?: never;
    url: '/v1/scrape';
};

export type PostV1ScrapeResponses = {
    /**
     * Job created
     */
    200: Job;
};

export type PostV1ScrapeResponse = PostV1ScrapeResponses[keyof PostV1ScrapeResponses];

export type PostV1CrawlData = {
    body: CrawlRequest;
    path?: never;
    query?: never;
    url: '/v1/crawl';
};

export type PostV1CrawlResponses = {
    /**
     * Job created
     */
    200: Job;
};

export type PostV1CrawlResponse = PostV1CrawlResponses[keyof PostV1CrawlResponses];

export type PostV1ResearchData = {
    body: ResearchRequest;
    path?: never;
    query?: never;
    url: '/v1/research';
};

export type PostV1ResearchResponses = {
    /**
     * Job created
     */
    200: Job;
};

export type PostV1ResearchResponse = PostV1ResearchResponses[keyof PostV1ResearchResponses];

export type GetV1JobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/jobs';
};

export type GetV1JobsResponses = {
    /**
     * Job list
     */
    200: JobList;
};

export type GetV1JobsResponse = GetV1JobsResponses[keyof GetV1JobsResponses];

export type DeleteV1JobsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/jobs/{id}';
};

export type DeleteV1JobsByIdResponses = {
    /**
     * Job canceled
     */
    200: StatusResponse;
};

export type DeleteV1JobsByIdResponse = DeleteV1JobsByIdResponses[keyof DeleteV1JobsByIdResponses];

export type GetV1JobsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/jobs/{id}';
};

export type GetV1JobsByIdResponses = {
    /**
     * Job
     */
    200: Job;
};

export type GetV1JobsByIdResponse = GetV1JobsByIdResponses[keyof GetV1JobsByIdResponses];

export type GetV1JobsByIdResultsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/jobs/{id}/results';
};

export type GetV1JobsByIdResultsResponses = {
    /**
     * Results (JSONL)
     */
    200: string;
};

export type GetV1JobsByIdResultsResponse = GetV1JobsByIdResultsResponses[keyof GetV1JobsByIdResultsResponses];
