// This file is auto-generated by @hey-api/openapi-ts

export type AuthOptions = {
    /**
     * Basic auth in user:pass form
     */
    basic?: string;
    headers?: {
        [key: string]: (string);
    };
    /**
     * Cookie strings like "name=value"
     */
    cookies?: Array<(string)>;
    loginUrl?: string;
    loginUserSelector?: string;
    loginPassSelector?: string;
    loginSubmitSelector?: string;
    loginUser?: string;
    loginPass?: string;
};

export type ScrapeRequest = {
    url: string;
    headless?: boolean;
    auth?: AuthOptions;
    timeoutSeconds?: number;
};

export type CrawlRequest = {
    url: string;
    maxDepth?: number;
    maxPages?: number;
    headless?: boolean;
    auth?: AuthOptions;
    timeoutSeconds?: number;
};

export type ResearchRequest = {
    query: string;
    urls: Array<(string)>;
    maxDepth?: number;
    maxPages?: number;
    headless?: boolean;
    auth?: AuthOptions;
    timeoutSeconds?: number;
};

export type Job = {
    id?: string;
    kind?: 'scrape' | 'crawl' | 'research';
    status?: 'queued' | 'running' | 'succeeded' | 'failed';
    createdAt?: string;
    updatedAt?: string;
    params?: {
        [key: string]: unknown;
    };
    resultPath?: string;
    error?: string;
};

export type kind = 'scrape' | 'crawl' | 'research';

export type status = 'queued' | 'running' | 'succeeded' | 'failed';

export type JobList = {
    jobs?: Array<Job>;
};

export type GetHealthzResponse = unknown;

export type PostV1ScrapeData = {
    requestBody: ScrapeRequest;
};

export type PostV1ScrapeResponse = Job;

export type PostV1CrawlData = {
    requestBody: CrawlRequest;
};

export type PostV1CrawlResponse = Job;

export type PostV1ResearchData = {
    requestBody: ResearchRequest;
};

export type PostV1ResearchResponse = Job;

export type GetV1JobsResponse = JobList;

export type GetV1JobsByIdData = {
    id: string;
};

export type GetV1JobsByIdResponse = Job;

export type GetV1JobsByIdResultsData = {
    id: string;
};

export type GetV1JobsByIdResultsResponse = string;

export type $OpenApiTs = {
    '/healthz': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: unknown;
            };
        };
    };
    '/v1/scrape': {
        post: {
            req: PostV1ScrapeData;
            res: {
                /**
                 * Job created
                 */
                200: Job;
            };
        };
    };
    '/v1/crawl': {
        post: {
            req: PostV1CrawlData;
            res: {
                /**
                 * Job created
                 */
                200: Job;
            };
        };
    };
    '/v1/research': {
        post: {
            req: PostV1ResearchData;
            res: {
                /**
                 * Job created
                 */
                200: Job;
            };
        };
    };
    '/v1/jobs': {
        get: {
            res: {
                /**
                 * Job list
                 */
                200: JobList;
            };
        };
    };
    '/v1/jobs/{id}': {
        get: {
            req: GetV1JobsByIdData;
            res: {
                /**
                 * Job
                 */
                200: Job;
            };
        };
    };
    '/v1/jobs/{id}/results': {
        get: {
            req: GetV1JobsByIdResultsData;
            res: {
                /**
                 * Results (JSONL)
                 */
                200: string;
            };
        };
    };
};