// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8741' | (string & {});
};

export type ExtractOptions = {
    /**
     * Template name (e.g. "article", "product")
     */
    template?: string;
    /**
     * Validate extraction against schema if present
     */
    validate?: boolean;
};

export type PipelineOptions = {
    preProcessors?: Array<string>;
    postProcessors?: Array<string>;
    transformers?: Array<string>;
};

export type ResearchEvidence = {
    url?: string;
    title?: string;
    snippet?: string;
    score?: number;
    simhash?: number;
    clusterId?: string;
    confidence?: number;
    citationUrl?: string;
};

export type ResearchEvidenceCluster = {
    id?: string;
    label?: string;
    confidence?: number;
    evidence?: Array<ResearchEvidence>;
};

export type ResearchCitation = {
    url?: string;
    anchor?: string;
    canonical?: string;
};

export type ResearchResult = {
    query?: string;
    summary?: string;
    confidence?: number;
    evidence?: Array<ResearchEvidence>;
    clusters?: Array<ResearchEvidenceCluster>;
    citations?: Array<ResearchCitation>;
};

export type HeaderKv = {
    key?: string;
    value?: string;
};

export type Cookie = {
    name?: string;
    value?: string;
    domain?: string;
    path?: string;
};

export type Token = {
    kind?: 'bearer' | 'basic' | 'api_key';
    value?: string;
    header?: string;
    query?: string;
    cookie?: string;
};

export type LoginFlow = {
    url?: string;
    userSelector?: string;
    passSelector?: string;
    submitSelector?: string;
    username?: string;
    password?: string;
};

export type TargetPreset = {
    name?: string;
    hostPatterns?: Array<string>;
    profile?: string;
    headers?: Array<HeaderKv>;
    cookies?: Array<Cookie>;
    tokens?: Array<Token>;
};

export type AuthProfile = {
    name?: string;
    parents?: Array<string>;
    headers?: Array<HeaderKv>;
    cookies?: Array<Cookie>;
    tokens?: Array<Token>;
    login?: LoginFlow;
    presets?: Array<TargetPreset>;
};

export type AuthVault = {
    version?: string;
    profiles?: Array<AuthProfile>;
    presets?: Array<TargetPreset>;
};

export type AuthProfilesResponse = {
    profiles?: Array<AuthProfile>;
};

export type AuthVaultImport = {
    /**
     * Simple filename only (no path, no directory separators, resolved relative to DATA_DIR)
     */
    path: string;
};

export type AuthVaultExport = {
    /**
     * Simple filename only (no path, no directory separators, resolved relative to DATA_DIR)
     */
    path: string;
};

export type StatusResponse = {
    status?: string;
};

export type ProxyConfig = {
    /**
     * Proxy URL (http://, https://, socks5://)
     */
    url?: string;
    /**
     * Username for proxy authentication
     */
    username?: string;
    /**
     * Password for proxy authentication
     */
    password?: string;
};

/**
 * Device emulation configuration for mobile/responsive content
 */
export type DeviceEmulation = {
    /**
     * Device preset name (e.g., "iPhone 14", "Pixel 7")
     */
    name?: string;
    /**
     * Viewport width in pixels
     */
    viewportWidth?: number;
    /**
     * Viewport height in pixels
     */
    viewportHeight?: number;
    /**
     * Device pixel ratio (e.g., 2.0 for Retina, 3.0 for iPhone)
     */
    deviceScaleFactor?: number;
    /**
     * User agent string for the device
     */
    userAgent?: string;
    /**
     * Whether to emulate mobile viewport
     */
    isMobile?: boolean;
    /**
     * Whether the device has touch capability
     */
    hasTouch?: boolean;
};

/**
 * Screenshot capture configuration for headless fetchers (chromedp, playwright). Ignored for HTTP fetcher.
 */
export type ScreenshotConfig = {
    /**
     * Whether to capture a screenshot of the page
     */
    enabled?: boolean;
    /**
     * Capture full page or just viewport
     */
    fullPage?: boolean;
    /**
     * Screenshot image format
     */
    format?: 'png' | 'jpeg';
    /**
     * JPEG quality (1-100), ignored for PNG
     */
    quality?: number;
    /**
     * Viewport width in pixels (0 = use default)
     */
    width?: number;
    /**
     * Viewport height in pixels (0 = use default)
     */
    height?: number;
    device?: DeviceEmulation;
};

export type AuthOptions = {
    /**
     * Basic auth in user:pass form
     */
    basic?: string;
    headers?: {
        [key: string]: string;
    };
    /**
     * Cookie strings like "name=value"
     */
    cookies?: Array<string>;
    /**
     * Query params applied to the request URL
     */
    query?: {
        [key: string]: string;
    };
    loginUrl?: string;
    loginUserSelector?: string;
    loginPassSelector?: string;
    loginSubmitSelector?: string;
    loginUser?: string;
    loginPass?: string;
    proxy?: ProxyConfig;
};

export type WebhookConfig = {
    /**
     * Webhook URL to receive job notifications
     */
    url?: string;
    /**
     * Events to subscribe to (default: ['completed'])
     */
    events?: Array<'completed' | 'failed' | 'canceled' | 'started' | 'all'>;
    /**
     * HMAC-SHA256 secret for signature verification
     */
    secret?: string;
};

/**
 * Payload sent to webhook endpoints on job events
 */
export type WebhookPayload = {
    /**
     * Unique identifier for this event
     */
    eventId?: string;
    /**
     * Type of event that triggered this webhook
     */
    eventType?: 'job.created' | 'job.started' | 'job.completed';
    /**
     * ISO 8601 timestamp of the event
     */
    timestamp?: string;
    /**
     * ID of the job this event relates to
     */
    jobId?: string;
    /**
     * Type of job
     */
    jobKind?: 'scrape' | 'crawl' | 'research';
    /**
     * Current job status
     */
    status?: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
    /**
     * Previous job status (if applicable)
     */
    prevStatus?: string;
    /**
     * Error message if job failed
     */
    error?: string;
    /**
     * Path to job results file
     */
    resultPath?: string;
    /**
     * Timestamp when job completed (for completed events)
     */
    completedAt?: string;
};

export type ScrapeRequest = {
    url: string;
    headless?: boolean;
    playwright?: boolean;
    authProfile?: string;
    auth?: AuthOptions;
    extract?: ExtractOptions;
    pipeline?: PipelineOptions;
    timeoutSeconds?: number;
    incremental?: boolean;
    proxy?: ProxyConfig;
    webhook?: WebhookConfig;
    screenshot?: ScreenshotConfig;
    device?: DeviceEmulation;
};

export type CrawlRequest = {
    url: string;
    maxDepth?: number;
    maxPages?: number;
    headless?: boolean;
    playwright?: boolean;
    authProfile?: string;
    auth?: AuthOptions;
    extract?: ExtractOptions;
    pipeline?: PipelineOptions;
    timeoutSeconds?: number;
    incremental?: boolean;
    proxy?: ProxyConfig;
    /**
     * Optional URL to a sitemap.xml file. If provided, URLs from the sitemap will be used as crawl seeds.
     */
    sitemapURL?: string;
    /**
     * If true, only crawl URLs from the sitemap, not the root URL. Requires sitemapURL to be set.
     */
    sitemapOnly?: boolean;
    /**
     * URL path patterns to include (glob syntax, e.g., /blog**). If specified, only matching URLs are crawled.
     */
    includePatterns?: Array<string>;
    /**
     * URL path patterns to exclude (glob syntax, e.g., /admin*). Excluded URLs take precedence over included ones.
     */
    excludePatterns?: Array<string>;
    webhook?: WebhookConfig;
    screenshot?: ScreenshotConfig;
    device?: DeviceEmulation;
};

export type ResearchRequest = {
    query: string;
    urls: Array<string>;
    maxDepth?: number;
    maxPages?: number;
    headless?: boolean;
    playwright?: boolean;
    authProfile?: string;
    auth?: AuthOptions;
    extract?: ExtractOptions;
    pipeline?: PipelineOptions;
    timeoutSeconds?: number;
    proxy?: ProxyConfig;
    webhook?: WebhookConfig;
    screenshot?: ScreenshotConfig;
    device?: DeviceEmulation;
};

export type Job = {
    id: string;
    kind: 'scrape' | 'crawl' | 'research';
    status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
    createdAt: string;
    updatedAt: string;
    /**
     * Job parameters. Sensitive fields (auth, headers, cookies, tokens, passwords, secrets) are redacted.
     */
    params?: {
        [key: string]: unknown;
    };
    /**
     * Error message if job failed. Secrets and filesystem paths are redacted.
     */
    error?: string;
    /**
     * Path to the screenshot file if screenshot capture was enabled
     */
    screenshotPath?: string;
};

export type JobList = {
    jobs?: Array<Job>;
};

export type HealthResponse = {
    status?: string;
    version?: string;
    components?: {
        [key: string]: ComponentStatus;
    };
};

export type ComponentStatus = {
    status?: string;
    message?: string;
    details?: {
        [key: string]: unknown;
    };
};

export type ErrorResponse = {
    /**
     * Human-readable error message
     */
    error: string;
};

export type Schedule = {
    /**
     * Unique schedule identifier
     */
    id: string;
    kind: 'scrape' | 'crawl' | 'research';
    /**
     * Interval between runs in seconds
     */
    intervalSeconds: number;
    /**
     * Next scheduled run time (RFC3339)
     */
    nextRun: string;
    /**
     * Schedule parameters
     */
    params: {
        [key: string]: unknown;
    };
};

export type ScheduleRequest = {
    kind: 'scrape' | 'crawl' | 'research';
    /**
     * Interval between runs in seconds
     */
    intervalSeconds: number;
    url?: string;
    query?: string;
    urls?: Array<string>;
    maxDepth?: number;
    maxPages?: number;
    headless?: boolean;
    playwright?: boolean;
    timeoutSeconds?: number;
    authProfile?: string;
    auth?: AuthOptions;
    extract?: ExtractOptions;
    pipeline?: PipelineOptions;
    incremental?: boolean;
    proxy?: ProxyConfig;
    /**
     * Optional URL to a sitemap.xml file. If provided, URLs from the sitemap will be used as crawl seeds.
     */
    sitemapURL?: string;
    /**
     * If true, only crawl URLs from the sitemap, not the root URL. Requires sitemapURL to be set.
     */
    sitemapOnly?: boolean;
    screenshot?: ScreenshotConfig;
    device?: DeviceEmulation;
};

export type ScheduleListResponse = {
    schedules: Array<Schedule>;
};

export type CrawlState = {
    /**
     * URL that was crawled
     */
    url: string;
    /**
     * ETag header value for incremental detection
     */
    etag: string;
    /**
     * Last-Modified header value
     */
    lastModified: string;
    /**
     * Hash of content for incremental detection
     */
    contentHash: string;
    /**
     * Timestamp of last scrape
     */
    lastScraped: string;
    /**
     * Depth at which this URL was found during crawl
     */
    depth?: number;
    /**
     * ID of the job that last scraped this URL
     */
    jobId?: string;
};

/**
 * WebSocket message envelope
 */
export type WsMessage = {
    /**
     * Message type
     */
    type: 'job_created' | 'job_started' | 'job_status_changed' | 'job_completed' | 'manager_status' | 'metrics' | 'ping' | 'pong' | 'subscribe_jobs' | 'unsubscribe_jobs';
    /**
     * Unix timestamp in milliseconds
     */
    timestamp: number;
    /**
     * Message payload (varies by type)
     */
    payload: unknown;
};

/**
 * Payload for job-related WebSocket events
 */
export type WsJobEventPayload = {
    jobId: string;
    kind: 'scrape' | 'crawl' | 'research';
    status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
    /**
     * Error message if job failed
     */
    error?: string;
    progress?: WsJobProgress;
    /**
     * Unix timestamp in milliseconds
     */
    updatedAt: number;
};

/**
 * Progress information for crawl jobs
 */
export type WsJobProgress = {
    pagesCrawled?: number;
    pagesTotal?: number;
    depthCurrent?: number;
    depthMax?: number;
};

/**
 * Payload for manager status updates
 */
export type WsManagerStatusPayload = {
    /**
     * Number of jobs in queue
     */
    queuedJobs: number;
    /**
     * Number of currently running jobs
     */
    activeJobs: number;
};

/**
 * Performance metrics and rate limiting status
 */
export type MetricsResponse = {
    /**
     * Requests per second over the retention window
     */
    requestsPerSec?: number;
    /**
     * Success rate as percentage (0-100)
     */
    successRate?: number;
    /**
     * Average response time in milliseconds
     */
    avgResponseTimeMs?: number;
    /**
     * Number of currently active requests
     */
    activeRequests?: number;
    /**
     * Total number of requests since startup
     */
    totalRequests?: number;
    fetcherUsage?: FetcherUsageBreakdown;
    /**
     * Rate limit status for all known hosts
     */
    rateLimitStatus?: Array<RateLimitStatus>;
    /**
     * Job throughput in jobs per minute
     */
    jobThroughputPerMin?: number;
    /**
     * Average job duration in milliseconds
     */
    avgJobDurationMs?: number;
    /**
     * Unix timestamp when metrics were captured
     */
    timestamp?: number;
};

/**
 * Usage counts per fetcher type
 */
export type FetcherUsageBreakdown = {
    /**
     * Number of HTTP requests
     */
    http?: number;
    /**
     * Number of Chromedp requests
     */
    chromedp?: number;
    /**
     * Number of Playwright requests
     */
    playwright?: number;
};

/**
 * Rate limit status for a single host
 */
export type RateLimitStatus = {
    /**
     * Hostname (sanitized, no paths or query params)
     */
    host?: string;
    /**
     * Queries per second limit
     */
    qps?: number;
    /**
     * Burst capacity
     */
    burst?: number;
    /**
     * Estimated current tokens available
     */
    tokens?: number;
    /**
     * Unix timestamp of last request to this host
     */
    lastRequest?: number;
};

/**
 * Render profile configuration for matching hosts
 */
export type RenderProfile = {
    /**
     * Unique profile name
     */
    name: string;
    /**
     * Host patterns to match (e.g., "example.com", "*.example.com")
     */
    hostPatterns: Array<string>;
    /**
     * Force specific rendering engine
     */
    forceEngine?: 'http' | 'chromedp' | 'playwright';
    /**
     * Skip HTTP probe and use headless engine
     */
    preferHeadless?: boolean;
    /**
     * Treat all pages as JS-heavy
     */
    assumeJsHeavy?: boolean;
    /**
     * Never use headless rendering
     */
    neverHeadless?: boolean;
    /**
     * JS heaviness threshold (0-1)
     */
    jsHeavyThreshold?: number;
    /**
     * Rate limit QPS for matching hosts (0 = use global default)
     */
    rateLimitQPS?: number;
    /**
     * Rate limit burst for matching hosts (0 = use global default)
     */
    rateLimitBurst?: number;
    block?: {
        resourceTypes?: Array<'image' | 'media' | 'font' | 'stylesheet' | 'other'>;
        urlPatterns?: Array<string>;
    };
    wait?: {
        mode?: 'dom_ready' | 'network_idle' | 'stability' | 'selector';
        selector?: string;
        networkIdleQuietMs?: number;
        minTextLength?: number;
        stabilityPollMs?: number;
        stabilityIterations?: number;
        extraSleepMs?: number;
    };
    timeouts?: {
        maxRenderMs?: number;
        scriptEvalMs?: number;
        navigationMs?: number;
    };
    screenshot?: {
        enabled?: boolean;
        fullPage?: boolean;
        format?: 'png' | 'jpeg';
        quality?: number;
        width?: number;
        height?: number;
    };
    device?: {
        name?: string;
        viewportWidth?: number;
        viewportHeight?: number;
        deviceScaleFactor?: number;
        userAgent?: string;
        isMobile?: boolean;
        hasTouch?: boolean;
    };
};

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzErrors = {
    /**
     * Service Unavailable
     */
    503: HealthResponse;
};

export type GetHealthzError = GetHealthzErrors[keyof GetHealthzErrors];

export type GetHealthzResponses = {
    /**
     * OK
     */
    200: HealthResponse;
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetV1AuthProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/profiles';
};

export type GetV1AuthProfilesErrors = {
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetV1AuthProfilesError = GetV1AuthProfilesErrors[keyof GetV1AuthProfilesErrors];

export type GetV1AuthProfilesResponses = {
    /**
     * Auth profiles
     */
    200: AuthProfilesResponse;
};

export type GetV1AuthProfilesResponse = GetV1AuthProfilesResponses[keyof GetV1AuthProfilesResponses];

export type DeleteV1AuthProfilesByNameData = {
    body?: never;
    path: {
        name: string;
    };
    query?: never;
    url: '/v1/auth/profiles/{name}';
};

export type DeleteV1AuthProfilesByNameErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteV1AuthProfilesByNameError = DeleteV1AuthProfilesByNameErrors[keyof DeleteV1AuthProfilesByNameErrors];

export type DeleteV1AuthProfilesByNameResponses = {
    /**
     * Deleted
     */
    200: StatusResponse;
};

export type DeleteV1AuthProfilesByNameResponse = DeleteV1AuthProfilesByNameResponses[keyof DeleteV1AuthProfilesByNameResponses];

export type PutV1AuthProfilesByNameData = {
    body: AuthProfile;
    path: {
        name: string;
    };
    query?: never;
    url: '/v1/auth/profiles/{name}';
};

export type PutV1AuthProfilesByNameErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Unsupported Media Type
     */
    415: ErrorResponse;
};

export type PutV1AuthProfilesByNameError = PutV1AuthProfilesByNameErrors[keyof PutV1AuthProfilesByNameErrors];

export type PutV1AuthProfilesByNameResponses = {
    /**
     * Auth profile saved
     */
    200: AuthProfile;
};

export type PutV1AuthProfilesByNameResponse = PutV1AuthProfilesByNameResponses[keyof PutV1AuthProfilesByNameResponses];

export type PostV1AuthImportData = {
    body: AuthVaultImport;
    path?: never;
    query?: never;
    url: '/v1/auth/import';
};

export type PostV1AuthImportErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Unsupported Media Type
     */
    415: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostV1AuthImportError = PostV1AuthImportErrors[keyof PostV1AuthImportErrors];

export type PostV1AuthImportResponses = {
    /**
     * Imported
     */
    200: StatusResponse;
};

export type PostV1AuthImportResponse = PostV1AuthImportResponses[keyof PostV1AuthImportResponses];

export type PostV1AuthExportData = {
    body: AuthVaultExport;
    path?: never;
    query?: never;
    url: '/v1/auth/export';
};

export type PostV1AuthExportErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Unsupported Media Type
     */
    415: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostV1AuthExportError = PostV1AuthExportErrors[keyof PostV1AuthExportErrors];

export type PostV1AuthExportResponses = {
    /**
     * Exported
     */
    200: StatusResponse;
};

export type PostV1AuthExportResponse = PostV1AuthExportResponses[keyof PostV1AuthExportResponses];

export type ListTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/templates';
};

export type ListTemplatesErrors = {
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListTemplatesError = ListTemplatesErrors[keyof ListTemplatesErrors];

export type ListTemplatesResponses = {
    /**
     * Template list
     */
    200: {
        /**
         * List of template names
         */
        templates?: Array<string>;
    };
};

export type ListTemplatesResponse = ListTemplatesResponses[keyof ListTemplatesResponses];

export type DeleteCrawlStatesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * URL of the crawl state to delete. If omitted, all states are cleared.
         */
        url?: string;
    };
    url: '/v1/crawl-states';
};

export type DeleteCrawlStatesErrors = {
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteCrawlStatesError = DeleteCrawlStatesErrors[keyof DeleteCrawlStatesErrors];

export type DeleteCrawlStatesResponses = {
    /**
     * Deleted
     */
    200: StatusResponse;
};

export type DeleteCrawlStatesResponse = DeleteCrawlStatesResponses[keyof DeleteCrawlStatesResponses];

export type ListCrawlStatesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of crawl states to return
         */
        limit?: number;
        /**
         * Number of crawl states to skip
         */
        offset?: number;
    };
    url: '/v1/crawl-states';
};

export type ListCrawlStatesErrors = {
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type ListCrawlStatesError = ListCrawlStatesErrors[keyof ListCrawlStatesErrors];

export type ListCrawlStatesResponses = {
    /**
     * Crawl states list
     */
    200: {
        crawlStates?: Array<CrawlState>;
    };
};

export type ListCrawlStatesResponse = ListCrawlStatesResponses[keyof ListCrawlStatesResponses];

export type PostV1ScrapeData = {
    body: ScrapeRequest;
    path?: never;
    query?: never;
    url: '/v1/scrape';
};

export type PostV1ScrapeErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Unsupported Media Type
     */
    415: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type PostV1ScrapeError = PostV1ScrapeErrors[keyof PostV1ScrapeErrors];

export type PostV1ScrapeResponses = {
    /**
     * Job created
     */
    200: Job;
};

export type PostV1ScrapeResponse = PostV1ScrapeResponses[keyof PostV1ScrapeResponses];

export type PostV1CrawlData = {
    body: CrawlRequest;
    path?: never;
    query?: never;
    url: '/v1/crawl';
};

export type PostV1CrawlErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Unsupported Media Type
     */
    415: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type PostV1CrawlError = PostV1CrawlErrors[keyof PostV1CrawlErrors];

export type PostV1CrawlResponses = {
    /**
     * Job created
     */
    200: Job;
};

export type PostV1CrawlResponse = PostV1CrawlResponses[keyof PostV1CrawlResponses];

export type PostV1ResearchData = {
    body: ResearchRequest;
    path?: never;
    query?: never;
    url: '/v1/research';
};

export type PostV1ResearchErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Unsupported Media Type
     */
    415: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Service Unavailable
     */
    503: ErrorResponse;
};

export type PostV1ResearchError = PostV1ResearchErrors[keyof PostV1ResearchErrors];

export type PostV1ResearchResponses = {
    /**
     * Job created
     */
    200: Job;
};

export type PostV1ResearchResponse = PostV1ResearchResponses[keyof PostV1ResearchResponses];

export type GetV1JobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of jobs to return
         */
        limit?: number;
        /**
         * Number of jobs to skip
         */
        offset?: number;
        /**
         * Filter jobs by status (omitted = all jobs)
         */
        status?: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
    };
    url: '/v1/jobs';
};

export type GetV1JobsErrors = {
    /**
     * Bad Request (invalid status parameter)
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetV1JobsError = GetV1JobsErrors[keyof GetV1JobsErrors];

export type GetV1JobsResponses = {
    /**
     * Job list
     */
    200: JobList;
};

export type GetV1JobsResponse = GetV1JobsResponses[keyof GetV1JobsResponses];

export type DeleteV1JobsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * If true, permanently delete the job. If false, cancel active jobs.
         */
        force?: boolean;
    };
    url: '/v1/jobs/{id}';
};

export type DeleteV1JobsByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteV1JobsByIdError = DeleteV1JobsByIdErrors[keyof DeleteV1JobsByIdErrors];

export type DeleteV1JobsByIdResponses = {
    /**
     * Operation succeeded
     */
    200: StatusResponse;
};

export type DeleteV1JobsByIdResponse = DeleteV1JobsByIdResponses[keyof DeleteV1JobsByIdResponses];

export type GetV1JobsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/jobs/{id}';
};

export type GetV1JobsByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
};

export type GetV1JobsByIdError = GetV1JobsByIdErrors[keyof GetV1JobsByIdErrors];

export type GetV1JobsByIdResponses = {
    /**
     * Job
     */
    200: Job;
};

export type GetV1JobsByIdResponse = GetV1JobsByIdResponses[keyof GetV1JobsByIdResponses];

export type GetV1JobsByIdResultsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * Output format for results (jsonl streams raw data, json converts to JSON array, md generates markdown report, csv generates CSV, xlsx generates Excel spreadsheet, parquet generates Apache Parquet for analytics)
         */
        format?: 'jsonl' | 'json' | 'md' | 'csv' | 'xlsx' | 'parquet';
        /**
         * Maximum number of result items to return (applies only to jsonl format)
         */
        limit?: number;
        /**
         * Number of result items to skip before returning results (applies only to jsonl format)
         */
        offset?: number;
    };
    url: '/v1/jobs/{id}/results';
};

export type GetV1JobsByIdResultsErrors = {
    /**
     * Bad Request (invalid format)
     */
    400: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
};

export type GetV1JobsByIdResultsError = GetV1JobsByIdResultsErrors[keyof GetV1JobsByIdResultsErrors];

export type GetV1JobsByIdResultsResponses = {
    /**
     * Results in requested format
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetV1JobsByIdResultsResponse = GetV1JobsByIdResultsResponses[keyof GetV1JobsByIdResultsResponses];

export type GetV1SchedulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/schedules';
};

export type GetV1SchedulesErrors = {
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetV1SchedulesError = GetV1SchedulesErrors[keyof GetV1SchedulesErrors];

export type GetV1SchedulesResponses = {
    /**
     * Schedule list
     */
    200: ScheduleListResponse;
};

export type GetV1SchedulesResponse = GetV1SchedulesResponses[keyof GetV1SchedulesResponses];

export type PostV1SchedulesData = {
    body: ScheduleRequest;
    path?: never;
    query?: never;
    url: '/v1/schedules';
};

export type PostV1SchedulesErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Unsupported Media Type
     */
    415: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostV1SchedulesError = PostV1SchedulesErrors[keyof PostV1SchedulesErrors];

export type PostV1SchedulesResponses = {
    /**
     * Schedule created
     */
    200: Schedule;
};

export type PostV1SchedulesResponse = PostV1SchedulesResponses[keyof PostV1SchedulesResponses];

export type DeleteV1SchedulesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/schedules/{id}';
};

export type DeleteV1SchedulesByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteV1SchedulesByIdError = DeleteV1SchedulesByIdErrors[keyof DeleteV1SchedulesByIdErrors];

export type DeleteV1SchedulesByIdResponses = {
    /**
     * Deleted
     */
    200: StatusResponse;
};

export type DeleteV1SchedulesByIdResponse = DeleteV1SchedulesByIdResponses[keyof DeleteV1SchedulesByIdResponses];

export type GetMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/metrics';
};

export type GetMetricsErrors = {
    /**
     * Method Not Allowed
     */
    405: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetMetricsError = GetMetricsErrors[keyof GetMetricsErrors];

export type GetMetricsResponses = {
    /**
     * Current metrics
     */
    200: MetricsResponse;
};

export type GetMetricsResponse = GetMetricsResponses[keyof GetMetricsResponses];

export type GetV1WsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/ws';
};

export type GetV1WsErrors = {
    /**
     * Bad Request (invalid upgrade request)
     */
    400: ErrorResponse;
};

export type GetV1WsError = GetV1WsErrors[keyof GetV1WsErrors];
