/**
 * Purpose: Provide generated OpenAPI client code for the Spartan Scraper web app.
 * Responsibilities: Expose generated API clients, request helpers, and schema types derived from `api/openapi.yaml`.
 * Scope: Generated code only; edit the OpenAPI contract or generator pipeline instead of this file.
 * Usage: Import generated APIs from adjacent web modules and regenerate with `make generate` after contract changes.
 * Invariants/Assumptions: This file is machine-generated, should stay in sync with the current contract, and may be overwritten at any time.
 */

// This file is auto-generated by @hey-api/openapi-ts

export type AuthToken = string | undefined;

export interface Auth {
  /**
   * Which part of the request do we use to send the auth?
   *
   * @default 'header'
   */
  in?: 'header' | 'query' | 'cookie';
  /**
   * Header or query parameter name.
   *
   * @default 'Authorization'
   */
  name?: string;
  scheme?: 'basic' | 'bearer';
  type: 'apiKey' | 'http';
}

export const getAuthToken = async (
  auth: Auth,
  callback: ((auth: Auth) => Promise<AuthToken> | AuthToken) | AuthToken,
): Promise<string | undefined> => {
  const token = typeof callback === 'function' ? await callback(auth) : callback;

  if (!token) {
    return;
  }

  if (auth.scheme === 'bearer') {
    return `Bearer ${token}`;
  }

  if (auth.scheme === 'basic') {
    return `Basic ${btoa(token)}`;
  }

  return token;
};
