// Package store provides persistent storage for batch operations using SQLite.
//
// This file is responsible for:
// - Batch CRUD operations (CreateBatch, GetBatch, UpdateBatchStatus)
// - Job-to-batch association management
// - Batch status aggregation queries
// - Listing jobs by batch with pagination
//
// This file does NOT handle:
// - Batch execution or job management (jobs package handles this)
// - Batch status calculation (model package handles this)
//
// Invariants:
// - Batch creation uses transactions to ensure consistency
// - Batch IDs are generated by callers (not the store)
// - All timestamps are stored as RFC3339Nano strings
package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/fitchmultz/spartan-scraper/internal/apperrors"
	"github.com/fitchmultz/spartan-scraper/internal/model"
)

// CreateBatch creates a new batch record and associated batch_jobs entries.
// This is a transactional operation - either all records are created or none.
func (s *Store) CreateBatch(ctx context.Context, batch model.Batch, jobIDs []string) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return apperrors.Wrap(apperrors.KindInternal, "failed to begin batch transaction", err)
	}
	defer tx.Rollback()

	// Insert batch record
	_, err = tx.ExecContext(ctx,
		`INSERT INTO batches (id, kind, status, job_count, created_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		batch.ID,
		string(batch.Kind),
		string(batch.Status),
		batch.JobCount,
		batch.CreatedAt.Format(time.RFC3339Nano),
		batch.UpdatedAt.Format(time.RFC3339Nano),
	)
	if err != nil {
		return apperrors.Wrap(apperrors.KindInternal, "failed to insert batch", err)
	}

	// Insert batch_jobs associations
	for i, jobID := range jobIDs {
		_, err = tx.ExecContext(ctx,
			`INSERT INTO batch_jobs (batch_id, job_id, idx) VALUES (?, ?, ?)`,
			batch.ID, jobID, i)
		if err != nil {
			return apperrors.Wrap(apperrors.KindInternal, "failed to insert batch_job association", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return apperrors.Wrap(apperrors.KindInternal, "failed to commit batch transaction", err)
	}

	return nil
}

// GetBatch retrieves a batch by ID.
// Returns apperrors.NotFound if the batch does not exist.
func (s *Store) GetBatch(ctx context.Context, id string) (model.Batch, error) {
	row := s.db.QueryRowContext(ctx,
		`SELECT id, kind, status, job_count, created_at, updated_at FROM batches WHERE id = ?`, id)

	var batch model.Batch
	var createdAt, updatedAt string

	err := row.Scan(&batch.ID, &batch.Kind, &batch.Status, &batch.JobCount, &createdAt, &updatedAt)
	if err != nil {
		return model.Batch{}, wrapScanError(err, "batch not found", "failed to get batch")
	}

	batch.CreatedAt, err = time.Parse(time.RFC3339Nano, createdAt)
	if err != nil {
		return model.Batch{}, apperrors.Wrap(apperrors.KindInternal, "failed to parse batch created_at", err)
	}

	batch.UpdatedAt, err = time.Parse(time.RFC3339Nano, updatedAt)
	if err != nil {
		return model.Batch{}, apperrors.Wrap(apperrors.KindInternal, "failed to parse batch updated_at", err)
	}

	return batch, nil
}

// UpdateBatchStatus updates the batch status and updated_at timestamp.
func (s *Store) UpdateBatchStatus(ctx context.Context, id string, status model.BatchStatus) error {
	_, err := s.db.ExecContext(ctx,
		`UPDATE batches SET status = ?, updated_at = ? WHERE id = ?`,
		string(status),
		time.Now().Format(time.RFC3339Nano),
		id,
	)
	if err != nil {
		return apperrors.Wrap(apperrors.KindInternal, "failed to update batch status", err)
	}
	return nil
}

// ListJobsByBatch returns jobs associated with a batch, ordered by batch_jobs index.
func (s *Store) ListJobsByBatch(ctx context.Context, batchID string, opts ListOptions) ([]model.Job, error) {
	opts = opts.Defaults()

	rows, err := s.db.QueryContext(ctx,
		`SELECT j.id, j.kind, j.status, j.created_at, j.updated_at, j.spec_version, j.spec_json, j.result_path, j.error, j.started_at, j.finished_at, j.selected_engine
		 FROM jobs j
		 INNER JOIN batch_jobs bj ON j.id = bj.job_id
		 WHERE bj.batch_id = ?
		 ORDER BY bj.idx ASC
		 LIMIT ? OFFSET ?`,
		batchID, opts.Limit, opts.Offset,
	)
	if err != nil {
		return nil, apperrors.Wrap(apperrors.KindInternal, "failed to list jobs by batch", err)
	}
	defer rows.Close()

	return s.scanJobs(rows)
}

// CountJobsByBatchAndStatus returns job counts per status for a batch.
func (s *Store) CountJobsByBatchAndStatus(ctx context.Context, batchID string) (model.BatchJobStats, error) {
	rows, err := s.db.QueryContext(ctx,
		`SELECT j.status, COUNT(*) as count
		 FROM jobs j
		 INNER JOIN batch_jobs bj ON j.id = bj.job_id
		 WHERE bj.batch_id = ?
		 GROUP BY j.status`,
		batchID,
	)
	if err != nil {
		return model.BatchJobStats{}, apperrors.Wrap(apperrors.KindInternal, "failed to count jobs by batch", err)
	}
	defer rows.Close()

	var stats model.BatchJobStats
	for rows.Next() {
		var status string
		var count int
		if err := rows.Scan(&status, &count); err != nil {
			return model.BatchJobStats{}, apperrors.Wrap(apperrors.KindInternal, "failed to scan status count", err)
		}
		switch model.Status(status) {
		case model.StatusQueued:
			stats.Queued = count
		case model.StatusRunning:
			stats.Running = count
		case model.StatusSucceeded:
			stats.Succeeded = count
		case model.StatusFailed:
			stats.Failed = count
		case model.StatusCanceled:
			stats.Canceled = count
		}
	}

	return stats, rows.Err()
}

// GetBatchJobIDs returns all job IDs associated with a batch, ordered by index.
func (s *Store) GetBatchJobIDs(ctx context.Context, batchID string) ([]string, error) {
	rows, err := s.db.QueryContext(ctx,
		`SELECT job_id FROM batch_jobs WHERE batch_id = ? ORDER BY idx ASC`,
		batchID,
	)
	if err != nil {
		return nil, apperrors.Wrap(apperrors.KindInternal, "failed to get batch job IDs", err)
	}
	defer rows.Close()

	var jobIDs []string
	for rows.Next() {
		var jobID string
		if err := rows.Scan(&jobID); err != nil {
			return nil, apperrors.Wrap(apperrors.KindInternal, "failed to scan job ID", err)
		}
		jobIDs = append(jobIDs, jobID)
	}

	return jobIDs, rows.Err()
}

// DeleteBatch removes a batch and its job associations (but not the jobs themselves).
func (s *Store) DeleteBatch(ctx context.Context, id string) error {
	// Due to ON DELETE CASCADE, deleting the batch will also delete batch_jobs entries
	_, err := s.db.ExecContext(ctx, `DELETE FROM batches WHERE id = ?`, id)
	if err != nil {
		return apperrors.Wrap(apperrors.KindInternal, "failed to delete batch", err)
	}
	return nil
}

// scanJobs scans job rows and returns a slice of jobs.
func (s *Store) scanJobs(rows *sql.Rows) ([]model.Job, error) {
	var results []model.Job
	for rows.Next() {
		job, err := s.scanJob(rows, false)
		if err != nil {
			return nil, apperrors.Wrap(apperrors.KindInternal, "failed to scan job row", err)
		}
		results = append(results, job)
	}
	return results, rows.Err()
}
