/**
 * Purpose: Provide generated OpenAPI client code for the Spartan Scraper web app.
 * Responsibilities: Expose generated API clients, request helpers, and schema types derived from `api/openapi.yaml`.
 * Scope: Generated code only; edit the OpenAPI contract or generator pipeline instead of this file.
 * Usage: Import generated APIs from adjacent web modules and regenerate with `make generate` after contract changes.
 * Invariants/Assumptions: This file is machine-generated, should stay in sync with the current contract, and may be overwritten at any time.
 */

// This file is auto-generated by @hey-api/openapi-ts

export type { Auth } from '../core/auth.gen';
export type { QuerySerializerOptions } from '../core/bodySerializer.gen';
export {
  formDataBodySerializer,
  jsonBodySerializer,
  urlSearchParamsBodySerializer,
} from '../core/bodySerializer.gen';
export { buildClientParams } from '../core/params.gen';
export { serializeQueryKeyValue } from '../core/queryKeySerializer.gen';
export { createClient } from './client.gen';
export type {
  Client,
  ClientOptions,
  Config,
  CreateClientConfig,
  Options,
  RequestOptions,
  RequestResult,
  ResolvedRequestOptions,
  ResponseStyle,
  TDataShape,
} from './types.gen';
export { createConfig, mergeHeaders } from './utils.gen';
